######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 13 17:18:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputfield.h mainwindow.h statistic.h wordpool.h
FORMS += mainwindow.ui
SOURCES += inputfield.cpp main.cpp mainwindow.cpp statistic.cpp wordpool.cpp
